# Generated by Django 5.0.7 on 2025-01-01 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_otp_created_datetime_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
