# Generated by Django 4.2.24 on 2025-11-01 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0008_alter_manager_user'),
        ('employe', '0008_alter_employe_user'),
        ('users', '0010_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_employee', to='employe.employe'),
        ),
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_manager', to='managers.manager'),
        ),
    ]
