# Generated by Django 5.0.7 on 2024-12-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('permanent_address', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'address',
                'db_table': 'employe_address',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('educational_qualifications', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_details', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'background',
                'verbose_name_plural': 'backgrounds',
                'db_table': 'employe_background',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('salary_details', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.IntegerField(blank=True, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=100, null=True)),
                ('pancard', models.CharField(blank=True, max_length=100, null=True)),
                ('pancard_file', models.FileField(blank=True, null=True, upload_to='pancard')),
                ('pf_fund', models.FloatField(default=0)),
                ('state_insurance_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'benefits',
                'verbose_name_plural': 'benefit',
                'db_table': 'employe_benefits',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=100, null=True)),
                ('relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'db_table': 'employe_contact',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('employment_Type', models.CharField(blank=True, choices=[('FT', 'FULL TIME'), ('PT', 'PART TIME'), ('CT', 'CONTRACT'), ('FR', 'FREELANCE')], max_length=100, null=True)),
                ('reporting_manager', models.CharField(blank=True, max_length=100, null=True)),
                ('work_location', models.CharField(blank=True, max_length=100, null=True)),
                ('employe_status', models.CharField(blank=True, choices=[('AT', 'ACTIVE'), ('PR', 'PROBATION'), ('LE', 'LEAVE')], max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('available_leaves', models.IntegerField(default=18)),
                ('leaves_taken', models.IntegerField(default=0)),
                ('medical_leaves_taken', models.IntegerField(default=0)),
                ('available_medical_leaves', models.IntegerField(default=14)),
                ('carryforward_leaves_taken', models.IntegerField(default=0)),
                ('carryforward_available_leaves', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'employe',
                'verbose_name_plural': 'employes',
                'db_table': 'employe_employe',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'holiday',
                'verbose_name_plural': 'holidays',
                'db_table': 'employe_holiday',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employe_type', models.CharField(blank=True, choices=[('AD', 'ADHAAR'), ('PS', 'PASSPORT'), ('SSN', ' SOCIAL SECURITY NUMBER (US)')], max_length=100, null=True)),
                ('work_authorization', models.CharField(blank=True, max_length=100, null=True)),
                ('skills', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'identification',
                'verbose_name_plural': 'identifications',
                'db_table': 'employe_identification',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_leaves', models.IntegerField(default=18)),
                ('leaves_taken', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'leave',
                'verbose_name_plural': 'leaves',
                'db_table': 'employe_leave',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LeaveReaquest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('leave_type', models.CharField(blank=True, choices=[('ML', 'MEDICAL LEAVE'), ('PR', 'PRIVILEGE'), ('CA', 'CASUAL')], max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='file')),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('rejection_date', models.DateField(blank=True, null=True)),
                ('leave_duration', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'leave_reaquest',
                'verbose_name_plural': 'leave_reaquests',
                'db_table': 'employe_leave_reaquest',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': ' skill',
                'verbose_name_plural': ' skills',
                'db_table': 'employe_skill',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'workSchedule',
                'verbose_name_plural': 'workSchedules',
                'db_table': 'employe_workSchedule',
                'ordering': ['-id'],
            },
        ),
    ]
