# Generated by Django 5.0.7 on 2024-12-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
