# Generated by Django 5.0.7 on 2025-06-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0003_alter_employe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereaquest',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('ML', 'Medical Leave'), ('AL', 'Annual Leave')], max_length=100, null=True),
        ),
    ]
