# Generated by Django 5.0.7 on 2025-06-24 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0004_alter_leavereaquest_leave_type'),
        ('managers', '0004_founder'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managers.manager'),
        ),
    ]
