# Generated by Django 4.2.24 on 2025-10-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0006_leaverequest_delete_leavereaquest'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='employe_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='employment_Type',
            field=models.CharField(blank=True, choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Internship', 'Internship')], max_length=100, null=True),
        ),
    ]
