# Generated by Django 4.2.24 on 2025-11-01 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0008_alter_employe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employe.employe'),
        ),
    ]
