# Generated by Django 4.2.24 on 2025-11-01 14:17

from django.db import migrations

def delete_leave_requests(apps, schema_editor):
    LeaveRequest = apps.get_model('employe', 'LeaveRequest')
    LeaveRequest.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0009_alter_leaverequest_employee'),
    ]

    operations = [
        migrations.RunPython(delete_leave_requests),
    ]
