# Generated by Django 4.2.24 on 2026-01-05 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0009_manager_founder'),
        ('employe', '0010_auto_20251101_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='founder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='founder_employees', to='managers.founder'),
        ),
    ]
