# Generated by Django 5.0.7 on 2026-01-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0012_leaverequest_cancellation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='carryforward_granted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='carryforward_used',
            field=models.IntegerField(default=0),
        ),
    ]
