# Generated by Django 4.2.24 on 2026-03-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0013_employe_carryforward_granted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='is_withdrawal_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_withdrawn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='withdrawal_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='withdrawal_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='withdrawal_requested_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='withdrawal_subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
