# Generated by Django 4.2.24 on 2026-05-25 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0013_unifiedleaverequest_is_withdrawal_requested_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employe', '0014_leaverequest_is_withdrawal_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='previous_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_employees', to='managers.manager'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
