# Generated by Django 4.2.24 on 2026-06-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0016_half_day_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='half_day_session',
            field=models.CharField(blank=True, choices=[('AM', 'Morning'), ('PM', 'Afternoon')], max_length=2, null=True),
        ),
    ]
