# Generated by Django 5.0.7 on 2025-06-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0004_founder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founder',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='founder_images/'),
        ),
    ]
