# Generated by Django 5.0.7 on 2025-06-26 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0005_alter_founder_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='available_leaves',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='manager',
            name='available_medical_leaves',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='manager',
            name='carryforward_available_leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manager',
            name='carryforward_leaves_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manager',
            name='leaves_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manager',
            name='medical_leaves_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ManagerLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('leave_type', models.CharField(blank=True, choices=[('ML', 'Medical Leave'), ('AL', 'Annual Leave')], max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='manager_leave_files')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_date', models.DateTimeField(blank=True, null=True)),
                ('leave_duration', models.IntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_manager_leaves', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='managers.manager')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_manager_leaves', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manager Leave Request',
                'verbose_name_plural': 'Manager Leave Requests',
                'db_table': 'manager_leave_request',
                'ordering': ['-id'],
            },
        ),
    ]
