# Generated by Django 4.2.24 on 2026-01-05 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0008_alter_manager_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='founder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='founder_managers', to='managers.founder'),
        ),
    ]
