# Generated by Django 4.2.24 on 2026-01-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0009_manager_founder'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontactmanager',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emergencycontactmanager',
            name='contact_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emergencycontactmanager',
            name='relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
