# Generated by Django 4.2.24 on 2026-01-05 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managers', '0010_emergencycontactmanager_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerleaverequest',
            name='cancellation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerleaverequest',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_old_manager_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managerleaverequest',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unifiedleaverequest',
            name='cancellation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unifiedleaverequest',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_unified_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unifiedleaverequest',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
