# Generated by Django 4.2.24 on 2026-01-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0011_managerleaverequest_cancellation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='carryforward_granted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unifiedleaverequest',
            name='carryforward_used',
            field=models.IntegerField(default=0),
        ),
    ]
