# Generated by Django 4.2.24 on 2026-05-26 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0013_unifiedleaverequest_is_withdrawal_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='previous_reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_sub_managers', to='managers.manager'),
        ),
        migrations.AddField(
            model_name='manager',
            name='reporting_manager_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_managers', to='managers.manager'),
        ),
    ]
