# Generated by Django 4.2.24 on 2026-06-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0014_manager_previous_reporting_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedleaverequest',
            name='is_half_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='available_leaves',
            field=models.FloatField(default=18),
        ),
        migrations.AlterField(
            model_name='manager',
            name='available_medical_leaves',
            field=models.FloatField(default=14),
        ),
        migrations.AlterField(
            model_name='manager',
            name='carryforward_available_leaves',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='manager',
            name='carryforward_granted',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='manager',
            name='carryforward_leaves_taken',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='manager',
            name='leaves_taken',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='manager',
            name='medical_leaves_taken',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='unifiedleaverequest',
            name='carryforward_used',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='unifiedleaverequest',
            name='leave_duration',
            field=models.FloatField(default=0),
        ),
    ]
